language: r
cache: packages

before_install:
  - tlmgr update --all || true     # one package fails to update but that doesn't affect the outcome
  #- tlmgr install index
  #- tlmgr install unicode-math lualatex-math pdftexcmds infwarerr luaotfload
  #- luaotfload-tool --update

after_success:
  - Rscript -e 'pkgdown::build_site()'

addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
      #- unicode-math
      #- lualatex-math
      #- pdftexcmds
      #- infwarerr
      #- luaotfload

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: main
